[20170607]
バグ：
call()の出力結果が1呼び出し、つまり、1ログファイルで閉じられてしまうため、複数のログファイルを一括で処理することができない。
